name: Netflix Clone CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint eslint
          npm init -y
          npm install --save-dev prettier

      - name: Run HTML validation
        run: htmlhint "*.html"

      - name: Run CSS validation
        run: stylelint "**/*.css"
        continue-on-error: true

      - name: Run JavaScript validation
        run: eslint "**/*.js"
        continue-on-error: true

      - name: Run Prettier check
        run: npx prettier --check .
        continue-on-error: true

      - name: Optimize images
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          find . -type f -name "*.jpg" -exec convert {} -strip -quality 85 {} \;
          find . -type f -name "*.png" -exec convert {} -strip {} \;

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
